### ISSUE TITLE
libtcod-cffi/tdl vs. libtcodpy

### ISSUE THREAD

**Issue by nightblade9** [HexDecimal/libtcod-cffi#18]
Hi,

I'm fairly new to Python and `libtcod`. While following "the" main tutorial on RogueBasin, I ran into `libtcod-cffi`, which I understand as a "pythonic port" of `libtcod`.

As a Python developer, how can I choose between `libtcod` and `libtcod-cffi`? What are the advantages and disadvantages to each side?  [This Reddit thread](https://www.reddit.com/r/roguelikedev/comments/5df9ly/libtcodcffi_as_a_dropin_replacement_for_libtcodpy/) seems to capture a couple of points (Linux support, updates get integrated over time).

**Comment by HexDecimal** [comment]
libtcod-cffi was merged into tdl.  So the following assumes you'll use the libtcod-cffi API from the tdl package which is documented [here](https://python-tdl.readthedocs.io/en/latest/index.html).  The code examples given at the top of most of the tcod sub-module docs should give you an idea of the API additions made.

There are no tutorials for the libtcod-cffi API, and that's a big deal if you're just getting into it.  You could use tdl as a drop in replacement for libtcodpy and use the libtcod tutorials if you think tdl is easier to distribute.  The documentation is mostly complete but often lacks fine details.  If you have any questions about the API then I'll answer them.

Because libtcodpy uses ctypes you don't need to compile the module as a Python C extension, you only need the DLL files.  Of course, you'll still need to get a hold of those DLL's for libtcodpy.  You can find builds for Windows easily, and it's only a little harder to compile some for Linux, but it's difficult to compile for MacOS if you don't have easy access to the platform.  tdl puts compiled extensions for Windows and MacOS on the pypi repository for easy installs, but at the moment there are no longer automated builds for Linux.  tdl's readme will tell you the two commands needed to install tdl on Linux.

libtcodpy is also more compact since it only uses the ctypes module which is already included in Python while tdl needs to install the cffi module and the relatively large numpy modules.

libtcodpy is more or less a direct port of the C API.  For example, if you make an off-screen console then you will need to make a call to free it like in C, and if it goes out of Python's scope before that then you'll have a memory leak.  In tdl all memory handling is been given to Python so that it can free those resources automatically.

tdl has serialization support for every class except Image, which means you can pickle all of those objects.  This feature does not exist in libtcodpy.

There's also a abundance of print_character_at and set_tile_at type functions which do not scale well in Python.  Any performance issues you might have with libtcodpy will be because of the many calls you'll make to these functions.  This is the main reason numpy is included as it lets you access those attributes in large batches.  In tdl, you are given direct access to the memory used by Console objects and several other objects (except Images) which lets you write Python code that runs almost as fast as C code.

**Comment by nightblade9** [comment]
Thanks for this. I didn't realize this is a sub-module of TDL. I think your points summarize as follows:

- `libtcodpy` provides binaries for Windows. `tdl` provides binaries for Windows and MacOS. (Both need to be compiled for Linux.)
- `libtcodpy` is smaller in size. `tdl` is larger, thanks to `numpy` modules.
- `libtcodpy` is written in C, and requires you to manage memory. `tdl` is written in Python and doesn't require you to handle memory.
- `tdl` allows you to serialize (pickle) everything except `Image` instances
- `libtcodpy` is slightly more performant than `tdl`.

Is that right?

Thanks for the detailed explanation.

**Comment by HexDecimal** [comment]
Good summaries, sorry if I'm being overly verbose.

> libtcodpy provides binaries for Windows. tdl provides binaries for Windows and MacOS. (Both need to be compiled for Linux.)

> libtcodpy is smaller in size. tdl is larger, thanks to numpy modules.

> tdl allows you to serialize (pickle) everything except Image instances

These are correct.

> libtcodpy is written in C, and requires you to manage memory. tdl is written in Python and doesn't require you to handle memory.

Both libtcodpy and tdl use a combination of libtcod's C code, custom C code, and Python code.

What matters is that instead allocating memory in C and managing that C pointer from Python, tdl allocates the memory from Python and passes it to C.  tdl usually creates some numpy arrays, creates Python owned structs pointing to those arrays, then passes the pointers for those structs to C.

> libtcodpy is slightly more performant than tdl.

I'm calling out libtcodpy functions like `console_put_char_ex(con, x, y, c, fore, back)`, if you ever need to update every tile on a Console then Python will have to do a lot of type conversion.  Smaller games will be fine, but if you want your game to have a large window and a small tile size you'll quickly notice a hard limit on the number of calls this function can handle in a single frame.  BearLibTerm has a similar problem.

The way tdl fixes this specific issue is to have the character data and foreground/background colors as numpy arrays.  You can crunch your data in numpy and dump it directly into the Console buffers skipping Python's slow path entirely.  This method is magnitudes faster than calling the above function on each tile.

tdl also uses very aggressive optimization flags when compiling its C extension, including link-time-optimization.  You can expect that some of the larger C functions called from tdl will perform slightly better than the DLL's available from the official site.

If you get performance issues, it's usually because of Python.  In the old legacy tdl API I made the incredibly poor choice of using Python callbacks for everything.  It did make code really easy to write, but it tanked performance.  The libtcod-cffi API handles performance much better by discouraging the use of callbacks and encouraging the use of numpy arrays and batch operations.
