### ISSUE TITLE
There is no libtcod 1.6.2, yet there are libtcod-cffi releases for it

### ISSUE THREAD

**Issue by rmtew** [HexDecimal/libtcod-cffi#7]
Hi,

Can you please not do releases for versions of libtcod that haven't been made?  This means that I have to say, reproduce your problem with libtcodpy or I cannot look at it, as I have no idea what version of libtcod you are actually having a problem with.

Thanks

**Comment by HexDecimal** [comment]
The 1.6.2 claim was me misreading the changelog.  I no longer mention the libtcod version at all in my later releases.

I don't want to raise an issue to you unless I can identify that the issue is in libtcod's C code on the latest master branch.  I'd prefer that my library doesn't cause you additional work.

libtcod-cffi now uses regression testing, so a scenario where you have to debug an issue with libtcod-cffi that I've missed is going to be rare.  If an issue does come up then the problem is that my regression tests didn't cover it.

With the regression tests in place, I'm free to do things much more insane then just using an in-between version of libtcod, since I'll know right away if anything is being broken.

If anyone has any issues with libtcod-cffi then I should be the one fixing those.  You'll then just need to worry about libtcodpy.

I think a good solution would to take [this unit test](https://github.com/HexDecimal/libtcod-cffi/blob/master/tests/test_libtcodpy.py) and set it up for libtcodpy.  I can make a pull request for this if you want.  You then add tests for any features you know can have problems.  Then libtcod-cffi can search for and must pass those tests during regression testing.  Running this test on both libtcodpy and libtcod-cffi is something I need to do anyway before I can take the current libtcod-cffi release out of alpha.

**Comment by rmtew** [comment]
Sorry for the delay, this has been sitting in the draft folder
procrastinated on, since I started writing.

Yes, please make a pull request.

There is one particular problem that I have with no associated libtcod
version number, which is the tutorial.  When I went over it and updated it
with admittedly minor changes for the 1.6 release, I decided to start
putting the recommended libtcod version number on it (which will always be
the latest release).

What I've been trying to do is update libtcod, and the tutorial, so that
all the common problems that pop up on /r/roguelikedev are addressed within
the tutorial to prevent them coming up again and again.  And updating
libtcod, and then specifying that specific version number in the tutorial,
and updating the tutorial with explicit text for each problem - may not
work with libtcod_cffi as a "backwards-compatible" alternative that has no
libtcod version number.

This is a new concern as there's a subset of people that struggle to get
libtcodpy working, and a reddit post in the last day or so suggested they
were going to put a reference to it as an alternative in the tutorial.  If
they haven't added a reference to it already, I'll do it myself, and
qualify the difference.

Anyway, better get this sent off.

Cheers,
Richard.
